# -*- coding: utf-8 -*-
"""AvaliacaoGestaoAcademica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wL0QfrGc2TjFJ7bbu2p24IkeKsBQooT4
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# 📂 Caminho do arquivo CSV com as respostas
file_path_csv = "Formulario-Avaliacao-Gestao-Academica-respostas-csv.csv"
df = pd.read_csv(file_path_csv)

# 🔄 Renomear colunas para facilitar a análise (MAIS CLARO)
df.columns = [
    "Timestamp", "Departamento", "TempoServico", "Genero",
    "ApoioDesenvolvimento", "Comunicacao", "DecisoesBeneficas",
    "RecursosAdequados", "OpiniaoValorizada", "AmbientePositivo",
    "Acessibilidade", "PoliticasDefinidas", "ApoioInovacao",
    "SatisfacaoRemuneracao", "SatisfacaoGestao", "ComentariosGerais",
    "ApoioDesenvolvimento2", "AcessibilidadeSugestoes", "Infraestrutura",
    "AmbienteColaborativo", "ApoioConferencias", "CompromissoQualidade",
    "ApoioInovacao2", "ComentariosFinais"
]

# ❌ Remover colunas irrelevantes para a análise quantitativa
df = df.drop(columns=["Timestamp", "ComentariosGerais", "ComentariosFinais"], errors="ignore")

# 🔢 Converter respostas textuais em valores numéricos usando replace() (mais rápido)
conversion_dict = {
    "1 - Discordo totalmente": 1,
    "2 - Discordo parcialmente": 2,
    "3 - Neutro": 3,
    "4 - Concordo parcialmente": 4,
    "5 - Concordo totalmente": 5
}

df.replace(conversion_dict, inplace=True)

# ⏳ Padronizar "TempoServico" para análise
tempo_servico_mapping = {
    "1 a 5 anos": "1-5 anos",
    "Mais de 5 anos": "5+ anos"
}
df["TempoServico"] = df["TempoServico"].replace(tempo_servico_mapping)

# 📊 Criar diretório para armazenar gráficos
output_dir = "graficos_avaliacao"
os.makedirs(output_dir, exist_ok=True)

# 🔹 Função para gerar e salvar gráficos (MELHORADA)
def gerar_graficos(coluna):
    print(f"📊 Gerando gráficos para: {coluna}")

    # 📊 Gráfico de barras para colunas categóricas (e.g., Departamento, Gênero)
    if df[coluna].dtype == "object":
        fig_bar = os.path.join(output_dir, f"{coluna}_bar.png")
        plt.figure(figsize=(8, 6))
        df[coluna].value_counts().sort_values().plot(kind="barh", color="skyblue")
        plt.title(f"Distribuição por {coluna}")
        plt.xlabel("Frequência")
        plt.ylabel(coluna)
        plt.savefig(fig_bar, bbox_inches="tight")  # Ajusta para evitar cortes
        plt.close()

    # 📈 Histograma e Boxplot para colunas numéricas (e.g., respostas das perguntas)
    if df[coluna].dtype in ["int64", "float64"]:
        # Histograma
        fig_hist = os.path.join(output_dir, f"{coluna}_hist.png")
        plt.figure(figsize=(8, 6))
        sns.histplot(df[coluna], bins=5, kde=True, color="royalblue")
        plt.title(f"Distribuição das Respostas - {coluna}")
        plt.xlabel("Nível de Concordância")
        plt.ylabel("Frequência")
        plt.xticks(range(1, 6))
        plt.savefig(fig_hist)
        plt.close()

        # Boxplot
        fig_box = os.path.join(output_dir, f"{coluna}_boxplot.png")
        plt.figure(figsize=(8, 6))
        sns.boxplot(x=df[coluna], color="skyblue")
        plt.title(f"Variação das Respostas - {coluna}")
        plt.xlabel("Nível de Concordância")
        plt.savefig(fig_box)
        plt.close()

# 🔄 Loop para gerar gráficos para todas as colunas (EXCETO "Comentários")
for coluna in df.columns:
    gerar_graficos(coluna)

print("✅ Todos os gráficos foram gerados e salvos na pasta 'graficos_avaliacao'.")